name: Test, Build and Pre-release
on: [push]

jobs:
  prerelease:
    name: 'Generate the pre-release'
    if: ${{ startsWith(github.event.head_commit.message, 'release v') }}
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      # setup build environment
      - name: 'Checkout the codebase'
        uses: actions/checkout@v4
      - name: 'Install CPython 3.9'
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: 'Install poetry'
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: '1.8'
      - name: 'Setup a local virtual environment'
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - name: 'Define a cache for the virtual environment'
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: 'Install the project dependencies'
        run: |
          poetry install

      # check the codebase
      - name: 'Check codebase'
        run: |
          poetry run pylint -d R0903,R0801 ./PyImportCheck/pyimportcheck
          poetry run mypy --strict ./PyImportCheck/pyimportcheck
          poetry run pytest

      # build the project
      - name: 'Build the project'
        run: |
          poetry build

      # generate / fetch / ensure needed information
      - name: 'Fetch project information'
        run: |
          sversion=$(echo ${{ github.event.head_commit.message }})
          tversion=$(echo $sversion | grep -oP 'v[0-9]+.[0-9]+.[0-9]+$')
          rversion=$(echo $sversion | grep -oP '[0-9]+.[0-9]+.[0-9]+$')
          echo "tversion=${tversion}" >> $GITHUB_ENV
          echo "rversion=${rversion}" >> $GITHUB_ENV
          echo "date_test=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          python ./PyImportCheck/scripts/generate_release_notes.py \
            $tversion \
            ./PyImportCheck/scripts/release.md
          cat ./pyproject.toml | grep -oP \
            "^version( )*=( )*[\"']${rversion}[\"']$"

      # publish to TestPyPi
      - name: 'Publish package distributions to TestPyPI'
        uses: pypa/gh-action-pypi-publish@v1.9.0
        with:
          repository-url: 'https://test.pypi.org/legacy/'
          verbose: true

      # create the release
      - name: 'Create the release'
        uses: softprops/action-gh-release@v2
        with:
          name: '${{ env.tversion }} (${{ env.date_test }})'
          tag_name: ${{ env.tversion }}
          body_path: './PyImportCheck/scripts/release.md'
          files: |
            dist/pyimportcheck-*.whl
            dist/pyimportcheck-*.tar.gz
          prerelease: true
          make_latest: true
